/**
 * awkn-local-action-runner — 结构化报告生成器
 *
 * 吸收 qoder-action task-reporter.ts 的结构化模式。
 * 输出：Markdown（人读）+ JSON（机器读）。
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { createLogger } from '../core/logger.js';
import type { PipelineResult } from './types.js';

const logger = createLogger('ActionReporter');

/** 生成报告，返回 Markdown 文件路径 */
export function generateReport(result: PipelineResult, cwd: string): string {
  const reportsDir = resolve(cwd, 'reports');
  mkdirSync(reportsDir, { recursive: true });

  const date = result.startedAt.slice(0, 10);
  const shortId = result.runId.slice(0, 8);
  const mdPath = resolve(reportsDir, `${date}-${result.pipelineName}-${shortId}.md`);
  const jsonPath = mdPath.replace(/\.md$/, '.json');

  writeFileSync(mdPath, renderMarkdown(result), 'utf-8');
  writeFileSync(jsonPath, JSON.stringify(result, null, 2), 'utf-8');

  logger.info(`Report generated: ${mdPath}`);
  return mdPath;
}

function renderMarkdown(r: PipelineResult): string {
  const icon = (s: string): string => s === 'passed' ? '✅' : s === 'failed' ? '❌' : '⏭️';

  const lines: string[] = [
    `# Pipeline Report: ${r.pipelineName}`,
    '',
    '| 字段 | 值 |',
    '|------|-----|',
    `| Run ID | \`${r.runId}\` |`,
    `| 状态 | ${icon(r.status)} ${r.status.toUpperCase()} |`,
    `| 触发 | ${r.trigger} |`,
    `| 分支 | ${r.branch} |`,
    `| Commit | \`${r.commitSha}\` |`,
    `| 开始 | ${r.startedAt} |`,
    `| 结束 | ${r.finishedAt} |`,
    `| 耗时 | ${(r.durationMs / 1000).toFixed(1)}s |`,
    '',
    '## Jobs',
    '',
    '| Job | 状态 | 耗时 | Steps |',
    '|-----|------|------|-------|',
  ];

  for (const job of r.jobs) {
    const stepSummary = job.steps.map((s) => `${icon(s.status)} ${s.name}`).join('<br>');
    lines.push(`| ${job.name} | ${icon(job.status)} ${job.status} | ${(job.durationMs / 1000).toFixed(1)}s | ${stepSummary} |`);
  }

  // 失败详情
  const failedSteps = r.jobs.flatMap((j) => j.steps).filter((s) => s.status === 'failed');
  if (failedSteps.length > 0) {
    lines.push('', '## 失败详情', '');
    for (const s of failedSteps) {
      lines.push(`### ❌ ${s.name}`, '', '```', s.output.slice(0, 2000), '```', '');
    }
  }

  // Agent 摘要
  const agentSteps = r.jobs.flatMap((j) => j.steps).filter((s) => s.agentSummary);
  if (agentSteps.length > 0) {
    lines.push('', '## Agent 分析', '');
    for (const s of agentSteps) {
      lines.push(`### 🤖 ${s.name}`, '', s.agentSummary ?? '', '');
    }
  }

  // Gate 结果
  const gateSteps = r.jobs.flatMap((j) => j.steps).filter((s) => s.gateResults && s.gateResults.length > 0);
  if (gateSteps.length > 0) {
    lines.push('', '## Gate 结果', '', '| Gate | 结果 | 详情 |', '|------|------|------|');
    for (const s of gateSteps) {
      for (const g of s.gateResults ?? []) {
        lines.push(`| ${g.name} | ${g.passed ? '✅ PASS' : '❌ FAIL'} | ${(g.details ?? '').slice(0, 100)} |`);
      }
    }
  }

  lines.push('', '---', `Generated by awkn-action-runner at ${new Date().toISOString()}`);
  return lines.join('\n');
}
